### PR TITLE
Serve JS libs from our backend

### PR DESCRIPTION
**Pull request by pior**

### CODE REVIEW

**Comment by mlhamel** [comment]
While we are there, it seems we are only using jquery in https://github.com/mtlpy/mtlpyweb/blob/master/mtlpy/static/js/post_admin.js and specifically at:
https://github.com/mtlpy/mtlpyweb/blob/master/mtlpy/static/js/post_admin.js#L27
https://github.com/mtlpy/mtlpyweb/blob/master/mtlpy/static/js/post_admin.js#L34

It could probably be done in a separated PR but since we are crazy, why not removing entirely jquery?

**Comment by pior** [comment]
@mlhamel ok to ship this PR? 
It's incremental, there is much more to do but I think shiping this makes sense.

**Comment by merwok** [comment]
Local is faster than a CDN?  Or better in another way?

**Comment by mlhamel** [comment]
this make things easier for local development without internet and i feel the downside is not really huge since anyway it's compress and then cached by the browser

**Comment by merwok** [comment]
Ok!

**Comment by pior** [comment]
In production, we have Cloudflare, so the JS will be served by a CDN anyway. (ours will just have a slightly poorer hit ratio)

**Pull request merged**
